Разметка главной страницы проекта "Седона"
htmlacademy-htmlcss/2302933-sedona-36 pull request #2
Opened 2023-01-25 20:45 UTC by Petru4io0

2023-01-26 03:58 UTC, Dima-Dim requested changes
В форке вашего проекта выполните разметку страниц в файлах index.html и catalog.html
Про hotels.html ничего нет.

2023-01-26 03:58 UTC, Dima-Dim commented on index.html
> +            <img class="services-item-img" src="#" alt="Дом.">
https://up.htmlacademy.ru/htmlcss/36/module/2/item/19

2023-01-26 03:58 UTC, Dima-Dim commented on index.html
> +        <p class="contacts-phone">+7 (812) 812-12-12</p>
https://up.htmlacademy.ru/htmlcss/36/criteries#HTML-03

2023-01-26 03:58 UTC, Dima-Dim commented on index.html
> +        <h2 class="visually-hidden">Логотип</h2>
Этот скрытый заголовок лишний так же как и использовании для этого небольшого элемента секции.

2023-01-26 11:19 UTC, Petru4io0 commented on index.html
> +            <img class="services-item-img" src="#" alt="Дом.">
Исправил

2023-01-26 11:19 UTC, Petru4io0 commented on index.html
> +        <p class="contacts-phone">+7 (812) 812-12-12</p>
Исправил

2023-01-26 11:21 UTC, Petru4io0 commented on index.html
> +        <h2 class="visually-hidden">Логотип</h2>
Исправил, на макете логотип отображен, как отдельный блок, вот и решил запихнуть его в section. Понял, что блоком является только картинка)

2023-01-26 14:09 UTC, Petru4io0 commented
Можете, пожалуйста, поподробнее написать о недостатках, недочётах и хороших моментах, если они есть) Или давайте созвонимся для более подробного разбора моего кода.

2023-01-27 12:58 UTC, Dima-Dim commented
> Можете, пожалуйста, поподробнее написать о недостатках, недочётах и хороших моментах, если они есть) Или давайте созвонимся для более подробного разбора моего кода.

Когда удобно созвониться?

2023-01-27 14:31 UTC, merged