Базовая стилизация всех страниц
htmlacademy-htmlcss/2302933-sedona-36 pull request #4
Opened 2023-02-04 22:21 UTC by Petru4io0

2023-02-05 03:28 UTC, Dima-Dim requested changes
В целом хорошо.

2023-02-05 03:28 UTC, Dima-Dim commented on catalog.html
> +        <input class="subscribe-input" type="email" name="subscribe-email" placeholder="Ваш e-mail" required><button class="subscribe-button" type="submit">Подписаться</button>
Выглядит как будто `button` внутри `input`. `button` нужно перенести на новую строку и всё станет понятнее.

2023-02-05 03:28 UTC, Dima-Dim commented on styles/styles.css
> +body{
Чуть выше перед `{` были пробелы. Пусть он будет перед всеми `{`.
И между селекторами давай будем делать пусты строки
```
  ...
  background-color: #ffffff;
  color:#000000;
}

.navigation-link {
  font-size:20px;
  font-weight:700;
  ...
```
, а то как-то всё в куче.

2023-02-05 12:28 UTC, Petru4io0 commented on styles/styles.css
> +body{
Исправил

2023-02-05 12:28 UTC, Petru4io0 commented on catalog.html
> +        <input class="subscribe-input" type="email" name="subscribe-email" placeholder="Ваш e-mail" required><button class="subscribe-button" type="submit">Подписаться</button>
Исправил

2023-02-06 15:02 UTC, Dima-Dim commented on styles/styles.css
> +.pagination-link.pagination-current {
Лучше так не делать, а создавать класс, который можно будет стилизовать сам по чебе, а не в сочетании с чем, то. Собственно почеме не испльзовать просто `.pagination-current`?

2023-02-06 15:02 UTC, merged

2023-02-06 20:46 UTC, Petru4io0 commented on styles/styles.css
> +.pagination-link.pagination-current {
Хочу спросить почему?
я исправил

2023-02-08 03:51 UTC, Dima-Dim commented on styles/styles.css
> +.pagination-link.pagination-current {
Такой селектор сложнее для для применения браузером, ему нужно найти понять что на теге есть не один селектор, а их сочетание. Чем проще тем лучше и быстрее всё это будет работать. Да это супер микро оптимизация, но её применение не стоит каких то особых усилий, так что почему бы и нет.